apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-initdb-config
data:
  create_tables.sql: |
    CREATE DATABASE betterjenkins WITH OWNER = postgres;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: betterjenkins-db
  labels:
    app.kubernetes.io/name: betterjenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: betterjenkins
  template:
    metadata:
      labels:
        app.kubernetes.io/name: betterjenkins
    spec:
      volumes:
      - name: psql-initdb
        configMap:
          name: psql-initdb-config
      containers:
      - name: betterjenkins-db
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
        - name: psql-initdb
          mountPath: /docker-entrypoint-initdb.d
---
apiVersion: v1
kind: Service
metadata:
  name: betterjenkins-db
  labels:
    app.kubernetes.io/name: betterjenkins
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/name: betterjenkins