kind: PersistentVolume
apiVersion: v1
metadata:
  name:  betterjenkins-db  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app:  betterjenkins-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  betterjenkins-db  # Sets name of PVC
  labels:
    app:  betterjenkins-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: betterjenkins-db
  labels:
    app: betterjenkins-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: betterjenkins-db
  template:
    metadata:
      labels:
        app: betterjenkins-db
    spec:
      volumes:
      - name: betterjenkins-vol
        persistentVolumeClaim:
          claimName: betterjenkins-db
      containers:
      - name: betterjenkins-db
        image: postgres:15-alpine
        lifecycle:
            postStart:
              exec:
                command: [
                  "/bin/sh",
                  "-c",
                  "sleep 20 && echo 
                    \"SELECT 'CREATE DATABASE betterjenkins WITH OWNER = ''postgres''' 
                    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'betterjenkins')\\gexec\" 
                    | PGPASSWORD=$POSTGRES_PASSWORD psql -w -U $POSTGRES_USER"
                ]
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: betterjenkins-vol
---
apiVersion: v1
kind: Service
metadata:
  name: betterjenkins-db
  labels:
    app: betterjenkins-db
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: betterjenkins-db