apiVersion: apps/v1
kind: Deployment
metadata:
  name: betterjenkins-server
  labels:
    app: betterjenkins-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: betterjenkins-server
  template:
    metadata:
      labels:
        app: betterjenkins-server
    spec:
      serviceAccountName: betterjenkins
      containers:
      - name: betterjenkins-server
        image: tj1997/betterjenkins:server
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_NAME
          value: betterjenkins
        - name: DB_HOST
          value: betterjenkins-db
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: MINIO_ACCESS_KEY
          value: minioadmin
        - name: MINIO_SECRET_KEY
          value: minioadmin
        - name: MINIO_API
          value: http://betterjenkins-minio-server:9000
---
apiVersion: v1
kind: Service
metadata:
  name: betterjenkins-server
  labels:
    app: betterjenkins-server
spec:
  selector:
    app: betterjenkins-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080