apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: betterjenkins
rules:
- apiGroups: ["batch"] # "" indicates the core API group
  resources: ["jobs"]
  verbs: ["get", "watch", "list", "create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: betterjenkins
  labels:
    app: betterjenkins-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: betterjenkins
subjects:
- kind: ServiceAccount
  name: betterjenkins
roleRef:
  kind: Role
  name: betterjenkins