apiVersion: batch/v1
kind: Job
metadata:
  name: betterjenkins-executor
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
      - name: betterjenkins-executor
        image: tj1997/betterjenkins:executor
        env:
        - name: DB_NAME
          value: betterjenkins
        - name: DB_HOST
          value: betterjenkins-db
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
      restartPolicy: Never
  backoffLimit: 5