apiVersion: batch/v1
kind: Job
metadata:
  name: betterjenkins-executor
  labels:
    app: betterjenkins-executor
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
      - name: betterjenkins-executor
        image: tj1997/betterjenkins:executor
        imagePullPolicy: Always
        env:
        - name: DB_NAME
          value: betterjenkins
        - name: DB_HOST
          value: betterjenkins-db
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: MINIO_ACCESS_KEY
          value: minioadmin
        - name: MINIO_SECRET_KEY
          value: minioadmin
        - name: MINIO_URL
          value: betterjenkins-minio-server:9000
      restartPolicy: Never
  backoffLimit: 5